### ISSUE TITLE
images and videos arnt responsive 

### ISSUE THREAD

**Issue by butlerx** [CoderDojo/cd-theme#17]
![img_3922](https://cloud.githubusercontent.com/assets/867930/18711995/47ef0ae8-8004-11e6-8082-1e3406d97b24.PNG)
![img_3924](https://cloud.githubusercontent.com/assets/867930/18712000/4b94e7b2-8004-11e6-9323-7627802e8dcb.PNG)

**Comment by DanielBrierton** [comment]
Fixed by #22
