### ISSUE TITLE
TODOs before deploying

### ISSUE THREAD

**Issue by adhorrig** [CoderDojo/cd-theme#7]
#**Content**

_Images_ (placeholders currently used):

Team headshots 125x125 or 200x200. (```page-foundation.twig```).
Board headshots 125x125 or 2002x00. (```page-foundation.twig```)
Sponsors images: 125x125 or 200x200. (```page-supporters.twig```).
CoderDojo movement is missing a banner (```page-movement.twig```).
Community Committee is missing a banner (```page-community-committee.twig```).
Philip stills needs to provide the images for each Kata path (```page-resources.twig```).

_Text:_

Create a dojo paragraphs of text need to be shortened (page-start-a-dojo).
Community committee is uses Lorem Ipsum. (```page-community-committee```).

_Pages:_

A reports page needs to be done. Most likely will be ```page-reports.twig```. It's purpose is to show off reports such as the annual report. No wireframes for this. Wanted by Rosa.

**Integrations:**

Currently the map (```map.twig```) makes an API call to Zen locally. This will need to be changed to production.

Stripe integration (```donate.twig```) is setup but have not verified a transaction.

**Migration:**

Another migration will need to be done to get the any posts which have been published since the last migration - around two / three weeks ago.

**Old posts:**

Currently old posts which have been migrated over do not display correctly. The reason for this is missing styling for certain elements. This is done inside ```single.twig```. For example, certain elements look okay which I have styled, such as videos. Post list items look messy as they have not been styled yet (see the minutes post). Giustina mentioned that not all posts need to have correct styling, only the latest ten or so. However it should still be looked at due to future posts that may be want to use one of the elements which has not got styling yet.

cc @rossoneill @danielbrierton

**Comment by Wardormeur** [comment]
@DanielBrierton can we close ?

**Comment by DanielBrierton** [comment]
👍
